spring:
  application:
    name: energy-router-sim
  datasource:
    url: jdbc:sqlite:energy_router.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: com.nessaj.ersim.config.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 36750


mqtt:
  host: 192.168.1.79
  port: 1883
  username: admin
  password: hddg@2009
  client-id: energy-router-sim
  publish-topic: energy-router/ReceiveTopic
  subscribe-topic: energy-router/SendTopic

#mqtt:
#  host: 124.221.130.19
#  port: 1883
#  username: admin
#  password: Nessaj@123
#  client-id: energy-router-sim
#  publish-topic: /energy-router/platform/receive
#  subscribe-topic: /energy-router/platform/send
  station-id: hd-energy-router-01